package com.aissa.aissatech.pojo;

/**
 * @author Camelia Boban
 *
 */
// default package
// Generated 29-dic-2012 23.36.39 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Anagrafica generated by hbm2java
 */
@Entity
@Table(name = "anagrafica", catalog = "aissatech", uniqueConstraints = @UniqueConstraint(columnNames = "codice_fiscale"))
public class Anagrafica implements java.io.Serializable {
	private static final long serialVersionUID = -8772849311167169823L;
	
	private Integer id;
	private String nome;
	private String cognome;
	private String matricola;
	private String codiceFiscale;
	private Date dataValidita;
	private Date dataScadenza;
	private Byte flagTipoCollab;
	

	public Anagrafica() {
	}

	public Anagrafica(String codiceFiscale) {
		this.codiceFiscale = codiceFiscale;
	}

	public Anagrafica(String nome, String cognome, String matricola,
			String codiceFiscale, Date dataValidita, Date dataScadenza,
			Byte flagTipoCollab) {
		this.nome = nome;
		this.cognome = cognome;
		this.matricola = matricola;
		this.codiceFiscale = codiceFiscale;
		this.dataValidita = dataValidita;
		this.dataScadenza = dataScadenza;
		this.flagTipoCollab = flagTipoCollab;		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome", length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "cognome", length = 45)
	public String getCognome() {
		return this.cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	@Column(name = "matricola", length = 8)
	public String getMatricola() {
		return this.matricola;
	}

	public void setMatricola(String matricola) {
		this.matricola = matricola;
	}

	@Column(name = "codice_fiscale", unique = true, nullable = false, length = 16)
	public String getCodiceFiscale() {
		return this.codiceFiscale;
	}

	public void setCodiceFiscale(String codiceFiscale) {
		this.codiceFiscale = codiceFiscale;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_validita", length = 10)
	public Date getDataValidita() {
		return this.dataValidita;
	}

	public void setDataValidita(Date dataValidita) {
		this.dataValidita = dataValidita;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_scadenza", length = 10)
	public Date getDataScadenza() {
		return this.dataScadenza;
	}

	public void setDataScadenza(Date dataScadenza) {
		this.dataScadenza = dataScadenza;
	}

	@Column(name = "flag_tipo_collab")
	public Byte getFlagTipoCollab() {
		return this.flagTipoCollab;
	}

	public void setFlagTipoCollab(Byte flagTipoCollab) {
		this.flagTipoCollab = flagTipoCollab;
	}

}
