package com.aissa.aissatech.pojo;

/**
 * @author Camelia Boban
 *
 */
// default package
// Generated 29-dic-2012 23.36.39 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Profilo generated by hbm2java
 */
@Entity
@Table(name = "profilo", catalog = "aissatech")
public class Profilo implements java.io.Serializable {
	private static final long serialVersionUID = -3998373076712377808L;
	
	private Integer id;
	private String descrizione;
	private Byte flagTipoProfilo;
	private Set<Login> logins = new HashSet<Login>(0);
	private Set<Abilitazione> abilitaziones = new HashSet<Abilitazione>(0);

	public Profilo() {
	}

	public Profilo(String descrizione, Byte flagTipoProfilo, Set<Login> logins,
			Set<Abilitazione> abilitaziones) {
		this.descrizione = descrizione;
		this.flagTipoProfilo = flagTipoProfilo;
		this.logins = logins;
		this.abilitaziones = abilitaziones;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "descrizione", length = 45)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "flag_tipo_profilo")
	public Byte getFlagTipoProfilo() {
		return this.flagTipoProfilo;
	}

	public void setFlagTipoProfilo(Byte flagTipoProfilo) {
		this.flagTipoProfilo = flagTipoProfilo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profilo")
	public Set<Login> getLogins() {
		return this.logins;
	}

	public void setLogins(Set<Login> logins) {
		this.logins = logins;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profilo")
	public Set<Abilitazione> getAbilitaziones() {
		return this.abilitaziones;
	}

	public void setAbilitaziones(Set<Abilitazione> abilitaziones) {
		this.abilitaziones = abilitaziones;
	}

}
